server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: mysql
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  redis:
     host: redis
     port: 6379
     jedis:
       pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



logging:
  level:
    com.example: info
    com.example.dao: debug
  file: /developer/apache-tomcat-7.0.73/logs/demo.log
  pattern:
    console: "%d -n %msg%n"

mybatis:
  mapper-locations: classpath:mappers/*.xml

swagger:
  enabled: true


jwt:
  secret: xiaozhu

